#!/bin/bash
if [ -z $VIRTUAL_ENV ] ; then
        echo ------------------------------------------------
        echo  This script must be called withit a virtualenv
        echo ------------------------------------------------
        echo
        exit
fi

BUILDFOLDER="appbuild"
NAME=midilamp
MAINPY=$NAME.py
ICON=lamp.icns

mkdir -p $BUILDFOLDER
rm -f $BUILDFOLDER/setup.py
for f in $MAINPY $ICON; do
	cp -r $f $BUILDFOLDER/
done

pushd $BUILDFOLDER
py2applet --make-setup $MAINPY $ICON
python setup.py py2app
popd

cp -r "$BUILDFOLDER/dist/$NAME.app" .

