#!/bin/bash
if [ -z $VIRTUAL_ENV ] ; then
        echo ------------------------------------------------
        echo  This script must be called withit a virtualenv
        echo ------------------------------------------------
        echo
        exit
fi

BUILDFOLDER="appbuild"
CSDPATCH="moire.csd"
MAINPY="moire.py"
PDPATCH="moiregui2.pd"

mkdir -p $BUILDFOLDER
rm -f $BUILDFOLDER/setup.py
for f in $MAINPY $PDPATCH $CSDPATCH pd moire_firmware; do
	cp -r $f $BUILDFOLDER/
done

pushd $BUILDFOLDER
py2applet --make-setup $MAINPY $PDPATCH $CSDPATCH ../assets/icon.icns
python setup.py py2app --resources pd,moire_firmware
popd

open "$BUILDFOLDER/dist"
